version: '3'
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts    
    user: root
    ports:
      - 8080:8080
    volumes:
      - jenkins:/data/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    container_name: postgres-db
    networks:
      - ruby
    links:
      - ruby-playground
    image: postgres
    environment:
      - POSTGRES_PASSWORD=default
      - PG_DATA=/data/postgres
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
  jenkins:
networks:
  ruby:
    name: ruby-network
    driver: bridge
